// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPWGeY8E59ADsZFo_Y5bNO7k7SQpMbdNM',
    appId: '1:322229939746:web:deb71e2d6202836747e47b',
    messagingSenderId: '322229939746',
    projectId: 'shoppingapp-c510c',
    authDomain: 'shoppingapp-c510c.firebaseapp.com',
    storageBucket: 'shoppingapp-c510c.firebasestorage.app',
    measurementId: 'G-SS25ZBJG7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMwnHQ9vLZD4rZ4rY9fTcgKN7ofs9HYOE',
    appId: '1:322229939746:android:ac8df5abb5132e9b47e47b',
    messagingSenderId: '322229939746',
    projectId: 'shoppingapp-c510c',
    storageBucket: 'shoppingapp-c510c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFh4iqClBGnYBZpM05M_hT3k1jcQ58zZE',
    appId: '1:322229939746:ios:7a6e4b62bf6366b847e47b',
    messagingSenderId: '322229939746',
    projectId: 'shoppingapp-c510c',
    storageBucket: 'shoppingapp-c510c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFh4iqClBGnYBZpM05M_hT3k1jcQ58zZE',
    appId: '1:322229939746:ios:7a6e4b62bf6366b847e47b',
    messagingSenderId: '322229939746',
    projectId: 'shoppingapp-c510c',
    storageBucket: 'shoppingapp-c510c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPWGeY8E59ADsZFo_Y5bNO7k7SQpMbdNM',
    appId: '1:322229939746:web:23a069353a5fba2947e47b',
    messagingSenderId: '322229939746',
    projectId: 'shoppingapp-c510c',
    authDomain: 'shoppingapp-c510c.firebaseapp.com',
    storageBucket: 'shoppingapp-c510c.firebasestorage.app',
    measurementId: 'G-7N3S05G2WH',
  );
}
